name: Vehicle Server CI
on:
  - push
  - pull_request
jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'
      - name: Check Go Version
        run: go version
      - name: Build application
        run: make all TAG="${{github.ref_name}}"
      - name: List dist output
        run: ls dist/
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push if on main branch
        if: contains('refs/heads/main', github.ref)
        run: |
          make release TAG="main"
      - name: Push if triggered by a tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          make release TAG="${{github.ref_name}}"
          